import { Inter } from "next/font/google";
import "./globals.css";
import { Web3Modal } from "../context/Web3Modal.tsx";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Header from "./components/header";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Web3Modal>
          <Header />
          {children}
        </Web3Modal>
        <ToastContainer />
      </body>
    </html>
  );
}
